### ISSUE TITLE
Embedded milvus could not be installed reporting "No matching distribution found for milvus"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/embd-milvus#1]
Embedded milvus could not be installed reporting "No matching distribution found for milvus"

(embedded-test-env-3.8) binbin@binbindeMacBook-Pro embeded_milvus % pip install milvus
ERROR: Could not find a version that satisfies the requirement milvus (from versions: none)
ERROR: No matching distribution found for milvus

python: 3.6 or 3.8
OS：mac intel

**Comment by soothing-rain** [comment]
I didn't not upload the Mac_x86 version: https://pypi.org/project/milvus/2.0.2rc2/

You can try upload your wheel from your machine.

**Comment by soothing-rain** [comment]
resolved.
