### ISSUE TITLE
Need to improve the installation of x86 macOS environment

### ISSUE THREAD

**Issue by soulteary** [milvus-io/embd-milvus#12]
hello maintainer 👋

The current dependency installation script lacks macOS support for x86 architecture:

code: https://github.com/milvus-io/embd-milvus/blob/main/milvus/lib/install_deps.sh#L80-L92

```bash
function install_mac_deps() {
...

  if [[ $(arch) == 'arm64' ]]; then
...
  fi
```

Currently it seems that only devices that support M1/M2 series chips.

**Comment by soothing-rain** [comment]
It does support x86 MAC systems.

```
  sudo xcode-select --install  > /dev/null 2>&1
  brew install boost libomp ninja tbb cmake llvm ccache
  brew uninstall grep
  brew install grep
  export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
  brew update && brew upgrade && brew cleanup
```

These are the required dependencies for x86 MAC.
