### ISSUE TITLE
Installation dependent files are not executable

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/embd-milvus#2]
1. When running `bash /tmp/e-milvus/lib/install_deps.sh`, the error `bash: /tmp/e-milvus/lib/install_deps.sh: No such file or directory` is reported. I have run `import milvus` and `milvus.before()` using the python command.

3. When I clone the repo and run `sh /home/zilliz_support/workspace/shiyu/embd-milvus/milvus/lib/install_deps.sh` it shows error `sh: 0: Can't open embd-milvus/milvus /lib /install_deps.sh`, I need to manually run `chmod a+x install_deps.sh` and it works. So can you change the mode of the "install_deps.sh" file to executable?

milvus version:2.0.2rc2

**Comment by soothing-rain** [comment]
1. Can you spot other libraries files under /tmp/e-milvus/lib? If so, it is likely that the file is not copied because you are using an old version of embedded Milvus.

2. Will do. Thanks!

**Comment by shiyu22** [comment]
There is no such directory: /tmp/e-milvus. And I will update milvus if it has updated.

**Comment by soothing-rain** [comment]
resolved.
