### ISSUE TITLE
Need to release latest version (v2.2.2)

### ISSUE THREAD

**Issue by liyaodev** [milvus-io/embd-milvus#26]
hello @soothing-rain, 

The current version used by embd-milvus remains at 2.1.0, and milvus released [2.2.2](https://github.com/milvus-io/milvus/releases/tag/v2.2.2) last month.

Not sure if there is an upgrade plan, thx

**Comment by xiaofan-luan** [comment]
@liyaodev 
We will release it soon!

**Comment by liyaodev** [comment]
@xiaofan-luan That's great. TYVM.

**Comment by matrixji** [comment]
@liyaodev 
Actually, you could check https://github.com/matrixji/python-milvus-server/
It's more simple and easy to run a standalone milvus server in python, also supports windows.

**Comment by xiaofan-luan** [comment]
> @liyaodev Actually, you could check https://github.com/matrixji/python-milvus-server/ It's more simple and easy to run a standalone milvus server in python, also supports windows.

Another big bang though!

**Comment by matrixji** [comment]
Now, python-milvus-server has been migrated to embd-milvus, and we have already released embd-milvus for milvus from 2.2.4 at Linux(x86_64), macOS(x86_64 and arm64), and windows(64bit)
`pip install -U milvus` and have a try.

btw: 2.2.5 will come soon.
